### ISSUE TITLE
Improved EDR Support for ensemble data

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/MetOceanDWG#5]
EDR does not current support subsettng by ensemble members, this has been identified as an issue by early users in the MetOcean domain.  The DWG should work with the EDR SWG to extend the EDR API to support the following functionality

    Enhancing the Collections/Instances metadata to describe the available ensemble members
    Add a query parameter to allow subsetting by the members dimension.

**Comment by solson-nws** [comment]
As discussed in 1/27/22 meeting:

DWG approval -- Beginning of March 2022
SWG approval -- End of March 2022
OAB review - Mid April 2022

**Comment by chris-little** [comment]
V1.1 draft encompasses support for ensembles, categorical and custom diemnsions, and at least two implementations demonstrated, so agreed to close at EDR API SWG 92, 2023-02-09.
