### ISSUE TITLE
EDR Support for HTTP POST

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/MetOceanDWG#6]
MetOcean users of EDR have identified a limitation caused by EDR only supporting GET requests and although the HTTP standards do not specifiy a limitation on the length of a GET request, in practice many HTTP servers have a maximum supported GET request length.  This has proved to be a problem due to the number of coordinates specified,  this issue would be resolved by adding support for HTTP POST to the EDR API specification.

**Comment by solson-nws** [comment]
As discussed in 1/27/22 meeting:

DWG approval -- Beginning of March 2022
SWG approval -- End of March 2022
OAB review - Mid April 2022

Separate conformance classes are envisionaged

**Comment by chris-little** [comment]
V1.1 draft encompassesHTTP POST, and at least two implementations demonstrated, so agreed to close at EDR API SWG 92, 2023-02-09.
